### ISSUE TITLE
shape_deltas [key] are all 0

### ISSUE THREAD

**Issue by jasonwongw** [mynalabsai/blendshapes-visualization#1]
Awesome project!
But I found a problem.  In 'demo-notebook.ipynb'  ,The cur_verts and verts_neutral variables are equal, resulting in shape_deltas.values() both being 0.weighted_deltas variables are also 0 when calculating weighted_deltas += cur_coeffs[key] * shape_deltas[key].Eventually, the blendshape weights do not affect the output coeff_ visualization.mp4

**Comment by jasonwongw** [comment]
This is the weighted_deltas variable for printing 
![image](https://github.com/mynalabsai/blendshapes-visualization/assets/108513330/58b389f9-302f-4856-ab98-48d1759ba111)

**Comment by pkorobov** [comment]
Hello, thank you for your interest in the article! Sorry for the late response, I've just seen the issue.

Well, I can agree with you, that `shape_deltas['_neutral']` always equals zero, but nothing is wrong with it. The thing is that we don't really need _neutral delta and we could even skip it in the loop. The whole point of delta blendshapes is to deform the neutral shape with deltas of *all the others*.

Moreover, you can notice that MediaPipe always outputs '_neutral' coefficient nearly equal to zero.

Talking about `weighted_deltas`, you just need to take a closer look. You see zeros, but this is just a small part of all the vertices coordinates. If it was fully filled with zeros we wouldn't get any animation :)

It just means that some vertices are not moved with deltas. For example, the hair of this model is the same for every expression. Look at the sum, for example. As you can see, there are not only zeros in the array.
<img width="272" alt="Screenshot 2024-02-26 at 1 37 07 PM" src="https://github.com/mynalabsai/blendshapes-visualization/assets/24700749/77ed9adc-556e-4d9d-a820-a9a63ca7b007">
